In [1]:
import requests
import time
import pandas as pd

In [2]:
def get_data(start=0, end=100, limit=100, wait_time=5):
    """Get a given number of observations from the launches endpoint
    of the Launch Library API.

    Args:
        start (int): The index of the first observation to return.
        end (int): The index of the last observation to return.
        limit (int): The maximum number of observations to return per batch.
        wait_time (int): The number of seconds to wait between batches.

    Returns:
        df (pandas.DataFrame): A dataframe containing the observations.
    """

    endpoint = "https://ll.thespacedevs.com/2.2.0/launch/previous/"
    df_list = []

    for offset in range(start, end, limit):
        params = {
            "format": "json",
            "limit": limit,
            "offset": offset
        }
        response = requests.get(endpoint, params=params)
        response.raise_for_status()
        df_list.append(extract_data(response))
        time.sleep(wait_time)

    df = pd.concat(df_list)
    return df

In [3]:
def extract_data(response):
    """Extract the data from the response object

    Args:
        response (requests.Response): The response object from a requests call
    Returns:
        df (pandas.DataFrame): A dataframe with the data from the response
    """

    data = response.json()
    try:
        df = pd.DataFrame(data["results"])
    except KeyError:
        df = pd.DataFrame()
        print(f"Warning: request {response.url} returned no data")
    
    return df

In [4]:
launch_df = get_data(start=0, end=300, limit=100, wait_time=2)

In [5]:
launch_df.head()

,id,url,slug,name,status,last_updated,net,window_end,window_start,probability,...,infographic,program,orbital_launch_attempt_count,location_launch_attempt_count,pad_launch_attempt_count,agency_launch_attempt_count,orbital_launch_attempt_count_year,location_launch_attempt_count_year,pad_launch_attempt_count_year,agency_launch_attempt_count_year
0,576b04d6-1962-4bda-b43f-0da4138d192d,https://ll.thespacedevs.com/2.2.0/launch/576b0...,falcon-9-block-5-starlink-group-3-4,Falcon 9 Block 5 | Starlink Group 3-4,"{'id': 3, 'name': 'Launch Successful', 'abbrev...",2022-08-31T06:57:21Z,2022-08-31T05:40:10Z,2022-08-31T05:40:10Z,2022-08-31T05:40:10Z,NaN,...,None,[],6279.0,702,96,191,115.0,9,9,39
1,67158b3c-201d-4450-be8a-990010c05b40,https://ll.thespacedevs.com/2.2.0/launch/67158...,falcon-9-block-5-starlink-group-4-23,Falcon 9 Block 5 | Starlink Group 4-23,"{'id': 3, 'name': 'Launch Successful', 'abbrev...",2022-08-31T03:19:23Z,2022-08-28T03:41:20Z,2022-08-28T03:41:20Z,2022-08-28T03:41:20Z,60.0,...,None,[],6278.0,855,151,190,114.0,25,18,38
2,a0d642d9-19ea-487d-8821-40c6f83e712f,https://ll.thespacedevs.com/2.2.0/launch/a0d64...,long-march-2d-beijing-3b,Long March 2D | Beijing-3B,"{'id': 3, 'name': 'Launch Successful', 'abbrev...",2022-08-31T03:35:50Z,2022-08-24T03:01:00Z,2022-08-24T03:31:00Z,2022-08-24T02:53:00Z,NaN,...,None,[],6277.0,112,37,382,113.0,8,6,29
3,5bdce7b6-0b8f-4df3-979e-3560654f9fe2,https://ll.thespacedevs.com/2.2.0/launch/5bdce...,kuaizhou-1a-chuangxin-16,Kuaizhou-1A | Chuangxin-16,"{'id': 3, 'name': 'Launch Successful', 'abbrev...",2022-08-31T03:16:26Z,2022-08-23T02:36:00Z,2022-08-23T02:44:00Z,2022-08-23T02:24:00Z,NaN,...,None,[],6276.0,175,21,17,112.0,8,1,2
4,4a114237-e8c5-4248-8d30-7a9026b86430,https://ll.thespacedevs.com/2.2.0/launch/4a114...,falcon-9-block-5-starlink-group-4-27,Falcon 9 Block 5 | Starlink Group 4-27,"{'id': 3, 'name': 'Launch Successful', 'abbrev...",2022-08-31T03:11:43Z,2022-08-19T19:21:20Z,2022-08-19T19:21:20Z,2022-08-19T19:21:20Z,70.0,...,None,[],6275.0,854,150,189,111.0,24,17,37